# Generated by Django 5.0.2 on 2024-05-18 17:59

import django.core.validators
import django.db.models.deletion
import serie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.PositiveIntegerField(default=serie.models.Serie.random_id, editable=False, primary_key=True, serialize=False)),
                ('reps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Las repeticiones deben ser mayores a 0.')])),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='El peso debe ser mayor a 0.')])),
                ('date', models.DateField()),
                ('duration', models.FloatField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
            ],
        ),
    ]
