# Generated by Django 5.0.2 on 2024-03-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='duration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
