# Generated by Django 5.0.2 on 2024-02-28 12:40

import serie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='id',
            field=models.PositiveIntegerField(default=serie.models.Serie.random_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
