# Generated by Django 4.2.7 on 2024-05-18 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='reps',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Las repeticiones deben ser mayores a 0.')]),
        ),
        migrations.AlterField(
            model_name='serie',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='El peso debe ser mayor a 0.')]),
        ),
    ]
