# Generated by Django 4.2.7 on 2024-04-18 19:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import owner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.PositiveIntegerField(default=owner.models.Owner.random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{6}', message='El número de teléfono debe contener solo dígitos y una longitud de 6 dígitos.')])),
                ('address', models.CharField(max_length=250)),
                ('customer_id', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('userCustom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
