# Generated by Django 5.0.2 on 2024-05-20 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[a-zA-Z\\sáéíóúÁÉÍÓÚ]*$', message='El nombre debe contener solo letras.')]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[a-zA-Z\\sáéíóúÁÉÍÓÚ]*$', message='El nombre debe contener solo letras.')]),
        ),
    ]
