# Generated by Django 5.0.2 on 2024-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='customer_id',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
