# Generated by Django 5.0.2 on 2024-02-28 12:40

import owner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_owner_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.PositiveIntegerField(default=owner.models.Owner.random_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
