# Generated by Django 4.2.7 on 2024-03-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='customer_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
