# Generated by Django 4.2.7 on 2024-04-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_owner_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
