# Generated by Django 4.2.7 on 2024-05-18 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_owner_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(
                max_length=50,
                validators=[django.core.validators.RegexValidator('^[a-z, A-Z]',
                message='El apellido debe contener letras.')]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(
                max_length=50,
                validators=[django.core.validators.RegexValidator('^[a-z, A-Z]',
                message='El nombre debe contener letras.')]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(
                max_length=9,
                validators=[django.core.validators.RegexValidator('^[0-9]{9}$',
                message='El número de teléfono debe contener solo dígitos y una longitud de 9 dígitos.')]),
        ),
    ]
