# Generated by Django 4.2.7 on 2024-05-19 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_owner_last_name_alter_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[a-zA-Z\\sáéíóúÁÉÍÓÚ]*$', message='El nombre debe contener solo letras.')]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[a-zA-Z\\sáéíóúÁÉÍÓÚ]*$', message='El nombre debe contener solo letras.')]),
        ),
    ]
