# Generated by Django 5.0.2 on 2024-02-28 12:40

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.PositiveIntegerField(default=client.models.Client.random_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
