# Generated by Django 4.2.7 on 2024-04-07 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_email_alter_client_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinLengthValidator(6),
                django.core.validators.MaxLengthValidator(6),
                django.core.validators.RegexValidator('^[0-9]+$',
                message='El número de teléfono debe contener solo dígitos.')]
            ),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipCode',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinLengthValidator(5),
                django.core.validators.MaxLengthValidator(5),
                django.core.validators.RegexValidator('^[0-9]{5}$',
                message='El código postal debe contener 5 dígitos numéricos.')]),
        ),
    ]
