# Generated by Django 4.2.7 on 2024-05-19 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_email_alter_client_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[a-zA-Z\\sáéíóúÁÉÍÓÚ]*$', message='El nombre debe contener solo letras.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[a-zA-Z\\sáéíóúÁÉÍÓÚ]*$', message='El nombre debe contener solo letras.')]),
        ),
    ]
