# Generated by Django 4.2.7 on 2024-04-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
