# Generated by Django 5.0.2 on 2024-02-28 12:40

import routine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='id',
            field=models.PositiveIntegerField(default=routine.models.Routine.random_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
