# Generated by Django 5.0.2 on 2024-05-18 17:59

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.PositiveIntegerField(default=equipment.models.Equipment.random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-z, A-Z]', message='El nombre debe contener letras.')])),
                ('brand', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
                ('description', models.TextField(validators=[django.core.validators.RegexValidator('^[a-z, A-Z]', message='La descripción debe contener letras.')])),
                ('muscular_group', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('other', 'Other')], max_length=20), size=8)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gym')),
            ],
            options={
                'unique_together': {('serial_number', 'gym')},
            },
        ),
    ]
