# Generated by Django 5.0.2 on 2024-03-17 09:12

import equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.PositiveIntegerField(default=equipment.models.Equipment.random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('muscular_group', models.CharField(choices=[('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('other', 'Other')], max_length=20)),
            ],
        ),
    ]
