# Generated by Django 4.1.3 on 2024-02-24 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('muscular_group', models.CharField(choices=[('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('other', 'Other')], max_length=20)),
                ('assessment', models.FloatField()),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gym')),
            ],
            options={
                'unique_together': {('serial_number', 'gym')},
            },
        ),
    ]
