# Generated by Django 5.0.2 on 2024-03-17 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gym'),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('serial_number', 'gym')},
        ),
    ]
