# Generated by Django 5.0.2 on 2024-02-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('zip_code', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
