# Generated by Django 4.1.3 on 2024-03-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
    ]
