# Generated by Django 5.0.2 on 2024-03-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
