# Generated by Django 4.2.7 on 2024-04-08 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_isclickable_alter_event_isnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.RegexValidator('^[a-z, A-Z]',
                message='La descripción debe contener letras.')]
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.RegexValidator('^[a-z, A-Z]',
                message='El nombre debe contener letras.')]
            ),
        ),
    ]
