# Generated by Django 4.2.7 on 2024-03-17 12:54

from django.db import migrations, models
import django.db.models.deletion
import workout.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('equipment', '0001_initial'),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.PositiveIntegerField(default=workout.models.Workout.random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('equipment', models.ManyToManyField(blank=True, to='equipment.equipment')),
                ('routine', models.ManyToManyField(blank=True, to='routine.routine')),
            ],
        ),
    ]
