# Generated by Django 4.2.7 on 2024-04-17 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(
                blank=True, max_length=30,
                validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(30)]
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(
                blank=True, max_length=150,
                validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(150)]
            ),
        ),
    ]
