# Generated by Django 4.2.7 on 2024-05-16 15:10

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'Ya existe un usuario con este nombre de usuario.'},
                help_text='Requerido. 150 caracteres o menos. Letras, dígitos y @/./+/-/_ solamente.',
                max_length=150, primary_key=True,
                serialize=False, unique=True, validators=[user.validators.UnicodeUsernameValidator()]),
        ),
    ]
