# Generated by Django 4.2.7 on 2024-04-18 19:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gym.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.PositiveIntegerField(default=gym.models.Gym.random_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-z, A-Z]', message='El nombre debe contener letras.')])),
                ('address', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-z, A-Z]', message='La dirección debe contener letras.')])),
                ('phone_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{9}', message='El número de teléfono debe contener solo dígitos y una longitud de 6 dígitos.')])),
                ('descripcion', models.CharField(max_length=500)),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='El código postal debe contener 5 dígitos numéricos.')])),
                ('email', models.EmailField(max_length=254)),
                ('subscription_plan', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('free', 'Free')], default='free', max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
                ('userCustom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
