# Generated by Django 5.0.2 on 2024-03-17 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner'),
        ),
    ]
