# Generated by Django 5.0.2 on 2024-02-28 12:40

import gym.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='id',
            field=models.PositiveIntegerField(default=gym.models.Gym.random_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
