# Generated by Django 4.2.7 on 2024-04-17 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_gym_address_alter_gym_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{9}', message='El número de teléfono debe contener solo dígitos y una longitud de 6 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='gym',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='El código postal debe contener 5 dígitos numéricos.')]),
        ),
    ]
