# Generated by Django 5.0.2 on 2024-02-28 12:40

import reservation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.PositiveIntegerField(default=reservation.models.Reservation.random_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
