# Generated by Django 5.0.2 on 2024-02-28 20:35

import django.db.models.deletion
import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '__first__'),
        ('equipment', '0001_initial'),
        ('gym', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.PositiveIntegerField(default=ticket.models.Ticket.random_id, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gym')),
            ],
        ),
    ]
