# Generated by Django 5.0.2 on 2024-02-28 12:40

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.PositiveIntegerField(default=ticket.models.Ticket.random_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
