# Generated by Django 4.2.7 on 2024-04-17 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(
                max_length=250,
                validators=[django.core.validators.RegexValidator('^[a-z, A-Z]',
                message='La descripción debe contener letras.')]
            ),
        ),
    ]
